name: OPA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OPA
        run: |
          set -euo pipefail
          rm -f opa opa064
          curl -fsSL -o opa https://openpolicyagent.org/downloads/v0.64.0/opa_linux_amd64_static
          chmod +x opa
          ./opa version
          ln -sf ./opa opa064 || true

      - name: fmt check
        run: ./opa064 fmt --fail policy/*.rego

      - name: static check
        run: ./opa064 check policy/*.rego

      - name: test
        run: ./opa064 test -v policy

      - name: smoke (optional)
        if: hashFiles('scripts/opa-smoke.sh') != ''
        run: bash scripts/opa-smoke.sh
