name: OPA CI
on:
  push:
  pull_request:
jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.64.0/opa_linux_amd64_static
          chmod +x opa && sudo mv opa /usr/local/bin/opa
      - name: Format check
        run: opa fmt --fail policy/*.rego
      - name: Static check
        run: opa check policy/*.rego
      - name: Unit tests
        run: opa test -v policy
