name: OPA Policy CI

on:
  push:
  pull_request:

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Rego fmt (check only)
        run: |
          opa fmt -c policy/*.rego

      - name: Rego compile check
        run: |
          opa check policy/*.rego

      - name: Run eval (PARTNER -> CONFIRM)
        run: |
          opa eval -f pretty \
            -i examples/sess_partner.jsonl \
            -d policy/agent.rego -d policy/labels.yaml \
            'data.agent.gate_decisions' > /dev/null

      - name: Run eval (UNKNOWN -> BLOCK)
        run: |
          opa eval -f pretty \
            -i examples/sess_unknown.jsonl \
            -d policy/agent.rego -d policy/labels.yaml \
            'data.agent.gate_decisions' > /dev/null

      - name: Run eval (TRUSTED -> ALLOW)
        run: |
          opa eval -f pretty \
            -i examples/sess_trusted.jsonl \
            -d policy/agent.rego -d policy/labels.yaml \
            'data.agent.gate_decisions' > /dev/null

      - name: Run eval (PARTNER + WARN -> CONFIRM)
        run: |
          opa eval -f pretty \
            -i examples/sess_partner_warn.jsonl \
            -d policy/agent.rego -d policy/labels.yaml -d policy/warn.json \
            'data.agent.gate_decisions' > /dev/null
