name: OPA CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # OPA v0.64.0 を取得
      - name: Install OPA 0.64.0
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.64.0/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Format (fail on diff)
        run: opa fmt --fail policy/*.rego

      - name: Static check
        run: opa check policy/*.rego

      - name: Unit tests (rego)
        run: opa test -v policy
