name: OPA CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "policy/**"
      - "examples/**"
      - ".github/workflows/opa-ci.yml"
      - "scripts/**"
  pull_request:
    branches: [ "main" ]   # ← PR は常に実行（paths フィルタなし）

permissions:
  contents: read

jobs:
  opa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.64.0/opa_linux_amd64_static
          chmod +x opa
          ./opa version
          ln -sf ./opa opa064   # idempotent

      - name: fmt check
        run: ./opa064 fmt --fail policy/*.rego

      - name: static check
        run: ./opa064 check policy/*.rego

      - name: test
        run: ./opa064 test -v policy

      - name: smoke (optional)
        if: ${{ always() }}
        run: |
          [ -x scripts/opa-smoke.sh ] && scripts/opa-smoke.sh || echo "(no smoke script)"
