name: OPA CI

on:
  push:
  pull_request:

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # OPA v0.64.0 をLinux用に取得（Makefileは ./opa064 を参照）
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.64.0/opa_linux_amd64_static
          chmod +x opa
          ./opa version
          ln -s ./opa opa064

      - name: fmt check
        run: make fmtcheck

      - name: static check
        run: make check

      - name: test
        run: make test
